### ISSUE TITLE
G Suite access level

### ISSUE THREAD

**Issue by reysy** [redsift/scrumbot#1]
Why your app needs that high access level?

<img width="285" alt="screen shot 2017-08-09 at 16 02 32" src="https://user-images.githubusercontent.com/866894/29118633-313accd6-7d1c-11e7-96d1-b1da6c9f9777.png">

**Comment by mkarliner** [comment]
Scrumbot is built on the Red Sift Cloud platform, which can, among other things use Gmail as an input to applications written for it. Currently, when you sign up for a Red Sift account, (which is what you are doing implicitly when installing scrumbot), the system also asks you for mail access, in case you are going to use mail processing Red Sift apps. We are going to change this so that the Google Oauth is separated from applications permissions, but it will take a little while.
Scrumbot's source code is in this repository, so you can check that it does not access you mail, and you can follow the video tutorial to install from scratch here. https://www.youtube.com/watch?v=RJZGaaEWEsc&t=862s

**Comment by pthomas931** [comment]
The permissions required to make the account make this Slack bot a deal breaker. Sure we can see the bot doesn't utilize our GMail, but that doesn't prevent the website's backend from having access.

**Comment by deepakprabhakara** [comment]
This issue has now been fixed. Scrumbot no longer asks for mail access and is decoupled from google login. @pthomas931 Apologies for the delay and I hope you'll give Scrumbot a try now.
